### ISSUE TITLE
npm run compile时报错了

### ISSUE THREAD

**Issue by zhaoweikai** [csr632/angular-aot-demo-with-ngc-webpack#1]
\> angular-aot-demo-with-ngc-webpack@0.0.0 compile D:\new-technologies-study\webpack\WebPack知识体系示例\指南篇\TypeScript\TypeScript+Angular+webpack---网上示例\a
ngular-aot-demo-with-ngc-webpack-master\angular-aot-demo-with-ngc-webpack-master
\> ngc -p ./tsconfig.json

src/app/app.component.ts(26,5): error TS2304: Cannot find name '$'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-aot-demo-with-ngc-webpack@0.0.0 compile: `ngc -p ./tsconfig.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-aot-demo-with-ngc-webpack@0.0.0 compile script 'ngc -p ./tsconfig.json'.

**Comment by csr632** [comment]
我[刚刚的commit](https://github.com/csr632/angular-aot-demo-with-ngc-webpack/commit/573fb0b03def411eb3315e7fdf0ee1c0570170dc)应该修复了这个问题。你pull一下再执行`npm run compile`就可以了。
